---

autodeploy_base_path: /opt/autodeploy
projects_base_path: "{{ autodeploy_base_path }}/projects"
resources_base_path: "{{ autodeploy_base_path }}/resources"

resource_dirs:
  - ISO
  - scaleio

git_repos:
  - { name: "slimer", repo: "https://github.com/csc/slimer.git" }
  - { name: "ansible-scaleio", repo: "https://github.com/csc/ansible-scaleio.git" }

autodeploy_support_pkgs:
  - dhcp
  - docker
  - firefox
  - genisoimage
  - httpd
  - ipmitool
  - iptables-services
  - ntp
  - python-netaddr
  - python-passlib
  - python-pip
  - python-xvfbwrapper
  - sshpass
  - unzip
  - vim
  - wget
  - xorg-x11-server-Xvfb
  - yum-utils
  - openssl-devel
  - glibc.i686
