---

- name: Check if RHEL DVD ISO file exists in the Hanlon image directory
  stat:
    path: "{{ iso_path }}/{{ rhel_iso_image }}"
    get_checksum: false
    get_md5: false
  register: rhel_iso
  tags: iso

- name: Find the RHEL DVD ISO file url
  selenium:
    url: "{{ rhel_download_url }}"
    username: "{{ rhn_user }}"
    password: "{{ rhn_pass }}"
    username_element_id: username
    password_element_id: password
    xpath: '//*[contains(@href,"{{ rhel_iso_image }}")]'
  register: rhel_get_url
  when: not (rhel_iso.stat.exists)
  tags: iso

- name: Download the RHEL DVD ISO file to /opt/autodeploy/resources/ISO
  get_url:
    url: "{{ rhel_get_url.url }}"
    dest: "{{ iso_path }}"
  when: not (rhel_iso.stat.exists)
  tags: iso

- name: Check if RHEL minimized image is in the Hanlon image directory
  stat:
    path: "{{ hnl_image_path }}/{{ hnl_rhel_min_image }}"
    get_checksum: false
    get_md5: false
  register: image_resource

- name: Create the Hanlon RHEL minimized ISO file if missing
  shell: "/opt/autodeploy/projects/dcaf/modules/bare-metal-os/roles/prepare/files/minimize-rhel-iso.sh -i {{ iso_path }}/{{ rhel_iso_image }} -o {{ hnl_image_path }}/{{ hnl_rhel_min_image }}"
  when: not (image_resource.stat.exists)
